name: IG Username Finder

on:
  workflow_dispatch:
  schedule:
    - cron: "2,17,32,47 * * * *"

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      BATCH: "20"

    steps:
      - name: Download repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install
        run: pip install -r requirements.txt

      - name: Run finder
        run: python main.py
